algorithm_description: Run HLS Phenometrics
algorithm_name: hls-phenometrics
algorithm_version: v0.1
build_command: HLS_phenometrics_maap/build-env.sh
disk_space: 8GB # test mem needed, up to 64GB
docker_container_url: mas.maap-project.org/root/maap-workspaces/custom_images/maap_base:v4.2.0
inputs:
  config: []
  file: []
  positional:
  - default: ''
    description: MGRS tile ID
    name: tile
    required: true
  - default: ''
    description: e.g. 2020
    name: target_year
    required: true
  - default: ''
    description: MAAP path where EVI2 or HLS scenes already exist
    name: data_dir
    required: false
  - default: "output"
    description: Location to write HLS scenes, EVI, and phemotrics
    name: output_dir
    required: true
queue: maap-dps-worker-8gb
repository_url: https://github.com/CQuinn8/HLS_phenometrics_maap
run_command: HLS_phenometrics_maap/run.sh
